Upload assets
inloco/actions-upload-assets pull request #1
Opened 2022-02-17 17:24 UTC by paulolieuthier

2022-02-17 17:37 UTC, tonidas approved these changes

2022-02-18 15:52 UTC, t0rr3sp3dr0 requested changes

2022-02-18 15:52 UTC, t0rr3sp3dr0 commented on action.yml
> +      script: |
This is essentially calling bash from node, we should use run instead.

2022-02-18 20:50 UTC, paulolieuthier commented on action.yml
> +      script: |
The reason I chose Javascript was to use the globber auxiliary module.

2022-02-18 20:50 UTC, paulolieuthier commented on action.yml
> +      script: |
But we can indeed use github-script to generate the file list and then execute the rest in a bash action.

2022-02-21 19:40 UTC, paulolieuthier commented
@t0rr3sp3dr0 reimplemented in bash script.

2022-02-24 20:56 UTC, paulolieuthier commented
@t0rr3sp3dr0 I missed the push.

2022-04-12 14:20 UTC, merged